### ISSUE TITLE
pdf 0.96

### ISSUE THREAD

**Issue by AxelAhlborn** [danwerner21/TI99_22#2]
On 0.96, the ATX Power support is missing (never mind, I use this: https://www.keelog.com/ti-99-4a-psu-modern-gray-au-replacement-ti-99-4a-power-supply-au-plug/). Page 3 of the pdf: Is it possible to use a different color ? If you print it on A4 you dont see anything because it is yellow on white. Greetings Axel

**Comment by danwerner21** [comment]
The ATX power plug was removed because it did not fit well in the case and was a bit overkill anyway.   I figured that screw terminals were more universal and made more sense in this instance.   

The colors are the default KiCad colors, but, I should be able to force new colors and reprint some time this weekend.
