### ISSUE TITLE
R22 and L7

### ISSUE THREAD

**Issue by AxelAhlborn** [danwerner21/TI99_22#5]
Is R22 a 361Ohm Resistor or 360Ohm because 361 is mentioned on SMD components but there is no axial resistor? 
L7, I only find 5.6uH axial, not 5.8uH, only SMDs or other special inductors.

So I will try R22 = 360Ohm and L7 = 5.6uH ?

**Comment by danwerner21** [comment]
That should work fine . . . 

 

 

From: AxelAhlborn ***@***.***> 
Sent: Thursday, July 27, 2023 1:18 PM
To: danwerner21/TI99_22 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [danwerner21/TI99_22] R22 and L7 (Issue #5)

 

Is R22 a 361Ohm Resistor or 360Ohm because 361 is mentioned on SMD components but there is no axial resistor?
L7, I only find 5.6uH axial, not 5.8uH, only SMDs or other special inductors.

So I will try R22 = 360Ohm and L7 = 5.6uH ?
