### ISSUE TITLE
Insert size on enclosure

### ISSUE THREAD

**Issue by SteveE3289** [danwerner21/TI99_22#9]
What is the insert size for the stand-off on the bottom half of the case enclosure to secure the main logic board?

**Comment by danwerner21** [comment]
I use M3x4x5mm M3 Threaded Inserts.   If it is FDM printed, you can just heat up the inserts and melt them in (I use a soldering iron) -- if it is resin printed you need to **_slightly_** enlarge the hole and use a touch of ca glue to hold the insert in place.  I typically put the insert on a long M3 screw so that it will sit in the right spot as it dries.  Obviously you would want to make sure you did not get any ca glue on the M3 screw or the inside threads of the insert.
